# Generated by Django 5.0.2 on 2024-03-05 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genre', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnimationAnime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('AnimTitle', models.TextField()),
                ('Location', models.URLField()),
                
            ],
        ),
        migrations.CreateModel(
            name='Series',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SeriesTitle', models.TextField()),
                ('Location', models.URLField()),
            ],
        ),
        migrations.RenameModel(
            old_name='Soaps',
            new_name='Movies',
        ),
    ]
