# Generated by Django 5.0.2 on 2024-03-05 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genre', '0002_animationanime_series_rename_soaps_movies'),
    ]

    operations = [
        migrations.CreateModel(
            name='Serie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SeriesTitle', models.TextField()),
                ('Location', models.URLField()),
            ],
        ),
        migrations.RenameModel(
            old_name='Series',
            new_name='Movie',
        ),
        migrations.RenameField(
            model_name='movie',
            old_name='SeriesTitle',
            new_name='MovieTitle',
        ),
    ]
